controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Author;
use app\models\Book;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // 'only' => ['logout', 'login'],
                'rules' => [
                    [
                        'actions' => ['login', 'logout'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index', 'create', 'update', 'show'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        
        if (isset($_REQUEST['Book']) && !empty($_REQUEST['Book']))
        {
            $book = $_REQUEST['Book'];
            $attrs = [];
            $date = '';
            if (!empty($book['author']))
            {
                $attrs['author_id'] = $book['author'];
            }
            if (!empty($book['name']))
            {
                $attrs['name'] = $book['name'];
            }
            if (!empty($book['date_from']))
            {
                if (empty($book['date_to'])) $book['date_to'] = date('Y.m.d', time());
                $date = ['between', 'date', date('Y-m-d', strtotime($book['date_from'])), date('Y-m-d', strtotime($book['date_to']))];
            }
            
            $books = Book::find()->with('author')->where($attrs)->andWhere($date)->orderBy('date_update DESC')->all();
        }
        else
            $books = Book::find()->with('author')->orderBy('date_update DESC')->all();

        $query = Author::find();
        $authors_db = $query->all();
        $authors = [];
        foreach ($authors_db as $key => $author) 
        {
            $authors[$author->id] = $author->firstname.' '.$author->lastname;
        }
        return $this->render('index', [
                'books' => $books,
                'authors' => $authors,
            ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionCreate()
    {

        if (isset($_REQUEST['Book']))
        {
            $uploads_files = array();
            $uploads_dir = $_SERVER['DOCUMENT_ROOT'].'web/images';
            $files = $_FILES['Book'];
            $path = '';
            if (!empty($files)) 
            {
                
                $tmp_name = $files["tmp_name"]['preview'];
                $name = $files["name"]['preview'];
                move_uploaded_file($tmp_name, "$uploads_dir/$name");
                $path = "$uploads_dir/$name";
            }
            $path = str_replace($_SERVER['DOCUMENT_ROOT'], '/', $path);
            $_REQUEST['Book']['preview'] = $path;
        }
        $model = new Book();
        if ($model->load($_REQUEST) && $model->save()) {
                return Yii::$app->response->redirect(['site/index']);
        } 
        else 
        {
            $query = Author::find();
            $authors_db = $query->all();
            $authors = [];
            foreach ($authors_db as $key => $author) 
            {
                $authors[$author->id] = $author->firstname.' '.$author->lastname;
            }
            return $this->render('create', ['model' => $model, 'authors' => $authors]);
        }
    }

    public function actionUpdate()
    {

        if (!empty($_FILES['Book']['name']['preview']))
        {
            $uploads_files = array();
            $uploads_dir = $_SERVER['DOCUMENT_ROOT'].'web/images';
            $files = $_FILES['Book'];
            $path = '';
            if (!empty($files)) 
            {
                
                $tmp_name = $files["tmp_name"]['preview'];
                $name = $files["name"]['preview'];
                move_uploaded_file($tmp_name, "$uploads_dir/$name");
                $path = "$uploads_dir/$name";
            }
            $path = str_replace($_SERVER['DOCUMENT_ROOT'], '/', $path);
            $_REQUEST['Book']['preview'] = $path;
        }
        elseif(isset($_REQUEST['Book']))
        {
            $_REQUEST['Book']['preview'] = $_REQUEST['Book']['preview_cache'];
        }
        $id = $_REQUEST['id'];
        $model = Book::find()->with('author')->one();
        if ($model->load($_REQUEST) && $model->save()) {
                return Yii::$app->response->redirect(['site/index']);
        } 
        else 
        {
            $query = Author::find();
            $authors_db = $query->all();
            $authors = [];
            foreach ($authors_db as $key => $author) 
            {
                $authors[$author->id] = $author->firstname.' '.$author->lastname;
            }
            
            return $this->render('update', ['model' => $model, 'authors' => $authors]);
        }
    }

    public function actionDelete() 
    {
        $id = $_REQUEST['id'];
        Book::find()->where(['id' => $id])->one()->delete();
        return $this->redirect(['site/index']);
    }

    public function actionShow()
    {
        $id = $_REQUEST['id'];
        $model = Book::find()->where(['id' => $id])->one();
        return $this->render('show', ['model' => $model]);
    }
}

views/site/create.php
<?php 
	use yii\bootstrap\ActiveForm; 
	use yii\helpers\Html;

?>
<div class="create book">
	<?php $form = ActiveForm::begin(array('options' => array('class' => 'ui form', 'enctype' => 'multipart/form-data')));
		echo '<div class="field">';
			echo $form->field($model, 'name')->textInput(['placeholder' => 'Название'])->label('Название') ;
		echo '</div>';
		echo '<div class="field">';
			echo $form->field($model, 'preview')->fileInput()->label('Обложка');
		echo '</div>';
		echo '<div class="three wide fields">';
			echo '<div class="field">';
				echo $form->field($model, 'date')->textInput(['placeholder' => 'Дата выпуска'])->label('Дата выпуска');
			echo '</div>';
			echo '<div class="field">';
				echo $form->field($model, 'author_id')->dropDownList($authors)->label('Автор');
			echo '</div>';
		echo '</div>';
		echo '<div class="field">';
			echo $form->field($model, 'description')->textArea()->label('Описание');
		echo '</div>';
		?>
		<div class="form-actions">
			<?php echo Html::submitButton($model->isNewRecord ? 'Добавить' : 'Сохранить', array('class' => 'ui button primary')); ?>
		</div>

		<?php ActiveForm::end(); ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm; 


$this->title = 'Библиотека';?>

<div class="site-index">
<form class='ui form' method="get">
	<div class="four wide fields">
		<div class="field">
			<select name="Book[author]">
				<?php foreach ($authors as $key => $author):?>
					<option value="<?php echo $key ?>"><?php echo $author ?></option>
				<?php endforeach ?>
			</select>
		</div>
		<div class="field">
			<input type="text" name="Book[name]" placeholder ='Название' value="<?php echo !empty($_REQUEST['Book']['name']) ? $_REQUEST['Book']['name'] : '' ?>">
		</div>
	</div>
	<div class="two wide fields">
		<div class="four wide fields">
			<div class="field">
				<label  style="padding-top: 7px;">Дата выхода книги</label>
			</div>
			<div class="field">
				<input type="text" name="Book[date_from]" value="<?php echo !empty($_REQUEST['Book']['date_from']) ? $_REQUEST['Book']['date_from'] : '' ?>">
			</div>
			<div class="field" align="center">
				<label  style="padding-top: 7px;">по</label>
			</div>
			<div class="field">
				<input type="text" name="Book[date_to]" value="<?php echo !empty($_REQUEST['Book']['date_to']) ? $_REQUEST['Book']['date_to'] : '' ?>">
			</div>
		</div>
	</div>
	<div class="field" align="right">
		<input type="submit" value='Искать' class="ui primary button">
	</div>
</form>
<table class="ui celled structured table">
  <thead>
    <tr>
      <th rowspan="2">Id</th>
      <th rowspan="2">Название</th>
      <th rowspan="2">Превью</th>
      <th rowspan="2">Автор</th>
      <th rowspan="2">Дата выхода книги</th>
      <th rowspan="2">Дата обновления</th>
      <th colspan="3" rowspan="2">Кнопки действия</th>
    </tr>
    
  </thead>
  <tbody>
  	<?php foreach ($books as $key => $book):?>
	    <tr>
	      <td><?php echo $book->id ?></td>
	      <td><?php echo $book->name ?></td>
	      <td>
	      		<a href="#" id='preview_<?php echo $book->id ?>'><img class="preview" src="<?php echo $book->preview ?>" alt="" width='100px'></a>
	      		<div id="block_preview_<?php echo $book->id ?>" class="big_prev">
    				<img src="<?php echo $book->preview ?>" alt="" width='500px'>
    			</div>
	      </td>

	      <td><?php echo $book->author->firstname.' '.$book->author->lastname ?></td>
	      <td><?php echo date('d.m.Y', strtotime($book->date)) ?></td>
	      <td><?php echo date('d.m.Y H:i', strtotime($book->date_update)) ?></td>
	      <td class="right aligned"><?php echo Html::a('ред', ['site/update', 'id' => $book->id]);?></td>
	      <td class="center aligned"><?php echo Html::a('просмотр', ['site/show', 'id' => $book->id]);?></td>
	      <td><?php echo Html::a('Удалить', ['site/delete', 'id' => $book->id], ['onclick' => 'confirm("Удалить?");']);?></td>
	      
	    </tr>
	<?php endforeach ?>
  </tbody>
</table>
    
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/show.php
<div class="ui items">
  <div class="item">
    <a class="ui large image">
      <img src="<?php echo $model->preview ?>">
    </a>
    <div class="content">
      <a class="header"><?php echo $model->name ?></a>
      <div class="meta">
      	Автор: 
        <span class="stay"><?php echo $model->author->firstname ?> <?php echo $model->author->lastname ?></span>
      </div>
      <div class="description">
        <p><?php echo $model->description ?></p>
      </div>
    </div>
  </div>
</div>

views/site/update.php
<?php 
	use yii\bootstrap\ActiveForm; 
	use yii\helpers\Html;

?>
<div class="create book">
	<?php $form = ActiveForm::begin(array('options' => array('class' => 'ui form', 'enctype' => 'multipart/form-data')));
		echo '<div class="field">';
			echo $form->field($model, 'name')->textInput(['placeholder' => 'Название'])->label('Название') ;
		echo '</div>';
		echo '<div class="field">';?>
			<img src="<?php echo $model->preview ?>" width='250px' alt="">
			<input type="hidden" value="<?php echo $model->preview ?>" name='Book[preview_cache]'> 
			<?
			echo $form->field($model, 'preview')->fileInput()->label('Обложка');
		echo '</div>';
		echo '<div class="three wide fields">';
			echo '<div class="field">';
				echo $form->field($model, 'date',['inputOptions' => ['value' => date( 'd.m.Y', strtotime($model->date) )]])->textInput(['placeholder' => 'Дата выпуска'])->label('Дата выпуска');
			echo '</div>';
			echo '<div class="field">';
				echo $form->field($model, 'author_id')->dropDownList($authors)->label('Автор');
			echo '</div>';
		echo '</div>';
		echo '<div class="field">';
			echo $form->field($model, 'description')->textArea()->label('Описание');
		echo '</div>';
		?>
		<div class="form-actions">
			<?php echo Html::submitButton($model->isNewRecord ? 'Добавить' : 'Сохранить', array('class' => 'ui button primary')); ?>
		</div>

		<?php ActiveForm::end(); ?>
</div>